// DO NOT EDIT. Automagically generated by the configure script.
// Will be removed by  make clean_all

	{ "cache", CacheComponent::Create, CacheComponent::GetAttribute },
	{ "cyclonevh", CycloneVHMachine::Create, CycloneVHMachine::GetAttribute },
	{ "dummy", DummyComponent::Create, DummyComponent::GetAttribute },
	{ "hp700rx", HP700RXMachine::Create, HP700RXMachine::GetAttribute },
	{ "i960_cpu", I960_CPUComponent::Create, I960_CPUComponent::GetAttribute },
	{ "m88k_cpu", M88K_CPUComponent::Create, M88K_CPUComponent::GetAttribute },
	{ "mvme187", MVME187Machine::Create, MVME187Machine::GetAttribute },
	{ "machine", MachineComponent::Create, MachineComponent::GetAttribute },
	{ "mainbus", MainbusComponent::Create, MainbusComponent::GetAttribute },
	{ "ram", RAMComponent::Create, RAMComponent::GetAttribute },
	{ "riscv_cpu", RISCV_CPUComponent::Create, RISCV_CPUComponent::GetAttribute },
	{ "riscv-virt", RISCVvirtMachine::Create, RISCVvirtMachine::GetAttribute },
	{ "testm88k", TestM88KMachine::Create, TestM88KMachine::GetAttribute },
