// DO NOT EDIT. Automagically generated by the configure script.
// Will be removed by  make clean_all

	StateVariable::RunUnitTests(nSucceeded, nFailed);
	SymbolRegistry::RunUnitTests(nSucceeded, nFailed);
	FileLoader::RunUnitTests(nSucceeded, nFailed);
	StringHelper::RunUnitTests(nSucceeded, nFailed);
	PauseCommand::RunUnitTests(nSucceeded, nFailed);
	ResetCommand::RunUnitTests(nSucceeded, nFailed);
	VersionCommand::RunUnitTests(nSucceeded, nFailed);
	ContinueBackwardsCommand::RunUnitTests(nSucceeded, nFailed);
	StepCommand::RunUnitTests(nSucceeded, nFailed);
	ContinueCommand::RunUnitTests(nSucceeded, nFailed);
	BackwardStepCommand::RunUnitTests(nSucceeded, nFailed);
	QuitCommand::RunUnitTests(nSucceeded, nFailed);
	CopyComponentCommand::RunUnitTests(nSucceeded, nFailed);
	MoveComponentCommand::RunUnitTests(nSucceeded, nFailed);
	ComponentFactory::RunUnitTests(nSucceeded, nFailed);
	GXemul::RunUnitTests(nSucceeded, nFailed);
	EscapedString::RunUnitTests(nSucceeded, nFailed);
	Checksum::RunUnitTests(nSucceeded, nFailed);
	FileLoader_raw::RunUnitTests(nSucceeded, nFailed);
	FileLoader_bout::RunUnitTests(nSucceeded, nFailed);
	FileLoader_aout::RunUnitTests(nSucceeded, nFailed);
	FileLoader_ELF::RunUnitTests(nSucceeded, nFailed);
	CommandInterpreter::RunUnitTests(nSucceeded, nFailed);
	Command::RunUnitTests(nSucceeded, nFailed);
	M88K_CPUComponent::RunUnitTests(nSucceeded, nFailed);
	RISCV_CPUComponent::RunUnitTests(nSucceeded, nFailed);
	I960_CPUComponent::RunUnitTests(nSucceeded, nFailed);
	CPUDyntransComponent::RunUnitTests(nSucceeded, nFailed);
	CPUComponent::RunUnitTests(nSucceeded, nFailed);
	RootComponent::RunUnitTests(nSucceeded, nFailed);
	DummyComponent::RunUnitTests(nSucceeded, nFailed);
	RAMComponent::RunUnitTests(nSucceeded, nFailed);
	CacheComponent::RunUnitTests(nSucceeded, nFailed);
	MachineComponent::RunUnitTests(nSucceeded, nFailed);
	MainbusComponent::RunUnitTests(nSucceeded, nFailed);
